[tool.poetry]
name = "pyconza-regbot"
version = "0.1.0"
description = ""
authors = ["Adam Piskorski <adam@piskorski.me>"]

[tool.poetry.dependencies]
python = "3.11.11"
discord-py = "^2.3.2"
httpx = "^0.25.0"
gspread-asyncio = "^1.9.0"
ics = "^0.7.2"
arrow = "^1.3.0"
google-api-python-client = "^2.184.0"
google-auth = "^2.41.1"
google-auth-httplib2 = "^0.2.0"
google-auth-oauthlib = "^1.2.2"
pytz = "^2025.2"

[tool.poetry.group.dev.dependencies]
mypy = "^1.5.1"
pytest = "^7.4.2"
black = "^23.9.1"
pre-commit = "^3.4.0"
ruff = "^0.0.291"
rich = "^13.6.0"
bpython = "^0.24"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 90
target-version = ['py311']

[tool.pytest.ini_options]
norecursedirs = [
    ".git",
    ".vscode",
    ".pytest_cache",
    ".mypy_cache",
    "__pycache__",
    "templates",
]

[tool.ruff]
select = [
    "A",
    "B",
    "BLE",
    "C4",
    "C90",
    "D",
    "DTZ",
    "E",
    "ERA",
    "F",
    "I",
    "ICN",
    "INP",
    "ISC",
    "N",
    "PGH",
    "PIE",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "T10",
    "T20",
    "TCH",
    "TID",
    "UP",
    "W",
]
ignore = ["E501", "D", "S311", "S101"]
line-length = 90
show-fixes = true
target-version = "py311"

[tool.ruff.pydocstyle]
convention = "google"
